# Credenciales del proyecto
sonar.projectKey=SaidJuniorProgrammer_red-social-distribuida
sonar.organization=saidjuniorprogrammer

# Rutas del código fuente y binarios (Descomentadas)
sonar.sources=frontend/src, backend/src/main/java
sonar.java.binaries=backend/target/classes

# Rutas de los tests para que no los cuente como código nuevo y no exija cubrirlos
sonar.tests=backend/src/test/java

# Ruta del reporte de cobertura de JaCoCo que GitHub Actions va a generar
sonar.coverage.jacoco.xmlReportPaths=backend/target/jacoco-report/jacoco.xml

# Exclusiones de carpetas que no requieren análisis de calidad
sonar.exclusions=**/node_modules/**, **/*.spec.ts, **/target/**, frontend/public/**