# Reemplaza estos valores con los que te dio SonarQube
sonar.projectKey=SaidJuniorProgrammer_red-social-distribuida
sonar.organization=saidjuniorprogrammer

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.coverage.exclusions=frontend/eslint.config.js,frontend/vite.config.js
# sonar.sources=frontend/src,backend/src/main/java
# sonar.java.binaries=backend/target/classes

# Exclusiones de carpetas que no requieren análisis de calidad
sonar.exclusions=**/node_modules/**, **/*.spec.ts, **/target/**, frontend/public/**, frontend/tests/**
