# ----------------------------------------
# Configuración de Neo4j (Grafo Social)
# ----------------------------------------
quarkus.neo4j.uri=bolt://localhost:7687
quarkus.neo4j.authentication.username=neo4j
quarkus.neo4j.authentication.password=password123

# ----------------------------------------
# Configuración de S3 (MinIO para Archivos)
# ----------------------------------------
quarkus.s3.endpoint-override=http://localhost:9090
quarkus.s3.aws.region=us-east-1
quarkus.s3.aws.credentials.type=static
quarkus.s3.aws.credentials.static-provider.access-key-id=admin
quarkus.s3.aws.credentials.static-provider.secret-access-key=1234
quarkus.s3.path-style-access=true

# Indicar a Quarkus que levante un Neo4j temporal en Docker durante los tests

%test.quarkus.neo4j.devservices.password=password123

%test.quarkus.s3.devservices.enabled=false