# ----------------------------------------
# Configuración de Neo4j (Grafo Social)
# ----------------------------------------
quarkus.neo4j.uri=bolt://localhost:7687
quarkus.neo4j.authentication.username=neo4j
quarkus.neo4j.authentication.password=password123

# ----------------------------------------
# Configuración de S3 (MinIO para Archivos)
# ----------------------------------------
quarkus.s3.endpoint-override=http://localhost:9090
quarkus.s3.aws.region=us-east-1
quarkus.s3.aws.credentials.type=static
quarkus.s3.aws.credentials.static-provider.access-key-id=admin
quarkus.s3.aws.credentials.static-provider.secret-access-key=1234
quarkus.s3.path-style-access=true

# ----------------------------------------
# Acceso del frontend durante el desarrollo
# ----------------------------------------
quarkus.http.cors.enabled=true
%dev.quarkus.http.cors.origins=http://localhost:5173
%dev.quarkus.http.cors.methods=GET,POST,OPTIONS
%dev.quarkus.http.cors.headers=Accept,Authorization,Content-Type

# ----------------------------------------
# Autenticación del chat en tiempo real
# ----------------------------------------
mp.jwt.verify.issuer=https://redsocial.com/issuer
quarkus.websockets-next.server.supported-subprotocols=bearer-token-carrier
quarkus.websockets-next.server.propagate-subprotocol-headers=true
